"""initial

Revision ID: 33becdbd96ba
Revises: 
Create Date: 2017-05-31 17:13:25.000844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33becdbd96ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('username_zh', sa.String(length=50), nullable=False),
    sa.Column('user_age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
