"""modify model structrue

Revision ID: 76f28dc9db68
Revises: 1385e2a594be
Create Date: 2017-06-08 16:19:56.691843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f28dc9db68'
down_revision = '1385e2a594be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'user_username_key', 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    op.drop_column('user', 'user_age')
    op.drop_column('user', 'username_zh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username_zh', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('user_age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(u'user_username_key', 'user', ['username'])
    # ### end Alembic commands ###
