"""reinit_2

Revision ID: 8160ce7a517c
Revises: a1ecd69cb57a
Create Date: 2017-06-08 16:52:35.482327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8160ce7a517c'
down_revision = 'a1ecd69cb57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('password', sa.String(length=150), nullable=False))
    op.add_column('t_user', sa.Column('user_age', sa.Integer(), nullable=False))
    op.add_column('t_user', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('t_user', sa.Column('username_zh', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'username_zh')
    op.drop_column('t_user', 'username')
    op.drop_column('t_user', 'user_age')
    op.drop_column('t_user', 'password')
    # ### end Alembic commands ###
