"""reinit_3

Revision ID: d0e8c52ca35c
Revises: 8160ce7a517c
Create Date: 2017-06-08 16:53:17.688970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e8c52ca35c'
down_revision = '8160ce7a517c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 't_user', ['id'])
    op.create_unique_constraint(None, 't_user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_user', type_='unique')
    op.drop_constraint(None, 't_user', type_='unique')
    # ### end Alembic commands ###
